
INSERT INTO cms_article_category (id, category_name, parent_Id, ordinal, category_type, category_code, create_time, create_account, update_time, update_account) VALUES (46, '新手上路', 0, 1, 'a', 'xinshoushanglu', null, null, null, null);
INSERT INTO cms_article_category (id, category_name, parent_Id, ordinal, category_type, category_code, create_time, create_account, update_time, update_account) VALUES (47, '购物指南', 0, 2, 'a', 'gouwuzhinan', null, null, null, null);
INSERT INTO cms_article_category (id, category_name, parent_Id, ordinal, category_type, category_code, create_time, create_account, update_time, update_account) VALUES (48, '支付方式', 0, 3, 'a', 'zhifufangshi', null, null, null, null);
INSERT INTO cms_article_category (id, category_name, parent_Id, ordinal, category_type, category_code, create_time, create_account, update_time, update_account) VALUES (51, '配送方式', 0, 5, 'a', 'peisongfangshi', null, null, null, null);
INSERT INTO cms_article_category (id, category_name, parent_Id, ordinal, category_type, category_code, create_time, create_account, update_time, update_account) VALUES (54, '特色服务', 0, 8, 'a', 'tesefuwu', null, null, null, null);
INSERT INTO cms_article_category (id, category_name, parent_Id, ordinal, category_type, category_code, create_time, create_account, update_time, update_account) VALUES (55, '关于我们', 0, 9, 'a', 'guanyuwomen', null, null, null, null);

INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (1,'admin','2016-04-04 15:06:27','admin','2016-04-04 15:56:39','关于ofmall','<h3 style=\"font-family:Lato, \'Helvetica Neue\', \'Microsoft YaHei\', Arial, Helvetica, sans-serif;font-size:18px;color:rgba(0, 0, 0, 0.8);background-color:#FAFAFA;\">\r\n	Ofmall技术说明\r\n</h3>\r\n<h3 style=\"font-family:Lato, \'Helvetica Neue\', \'Microsoft YaHei\', Arial, Helvetica, sans-serif;font-size:18px;color:rgba(0, 0, 0, 0.8);background-color:#FAFAFA;\">\r\n	后端技术\r\n</h3>\r\n<ul class=\"task-list\" style=\"font-size:14px;color:rgba(0, 0, 0, 0.8);font-family:Lato, \'Helvetica Neue\', \'Microsoft YaHei\', Arial, Helvetica, sans-serif;background-color:#FAFAFA;\">\r\n	<li>\r\n		核心框架: Spring Framework\r\n	</li>\r\n	<li>\r\n		数据库访问: Mybatis\r\n	</li>\r\n	<li>\r\n		视图框架: Spring MVC\r\n	</li>\r\n	<li>\r\n		页面视图: Freemarker/jsp\r\n	</li>\r\n	<li>\r\n		视图重写: urlrewrite\r\n	</li>\r\n	<li>\r\n		日志组件: logback\r\n	</li>\r\n	<li>\r\n		其他组件: commons-io,commons-fileupload,commons-beanutils,jackson,pinyin4j,aliyun,alipay,commons-lang\r\n	</li>\r\n</ul>\r\n<h3 style=\"font-family:Lato, \'Helvetica Neue\', \'Microsoft YaHei\', Arial, Helvetica, sans-serif;font-size:18px;color:rgba(0, 0, 0, 0.8);background-color:#FAFAFA;\">\r\n	<a class=\"anchor\" id=\"前端技术\" href=\"http://git.oschina.net/dinguangx/jshop#前端技术\"></a>前端技术\r\n</h3>\r\n<ul class=\"task-list\" style=\"font-size:14px;color:rgba(0, 0, 0, 0.8);font-family:Lato, \'Helvetica Neue\', \'Microsoft YaHei\', Arial, Helvetica, sans-serif;background-color:#FAFAFA;\">\r\n	<li>\r\n		JS框架： jquery1.9\r\n	</li>\r\n	<li>\r\n		CSS框架: Bootstrap3.3.2\r\n	</li>\r\n	<li>\r\n		后台集成框架: StartBootstrap SB admin V2 / jquery UI\r\n	</li>\r\n	<li>\r\n		富文本编辑器: KindEditor\r\n	</li>\r\n	<li>\r\n		树形组件: zTree\r\n	</li>\r\n	<li>\r\n		日期控件: My97DatePicker\r\n	</li>\r\n	<li>\r\n		客户端校验：<a href=\"http://niceue.com/validator/\">nice validator</a> \r\n	</li>\r\n	<li>\r\n		树形表格组件： jquery-treegrid(暂定)\r\n	</li>\r\n	<li>\r\n		文件上传: uploadify\r\n	</li>\r\n</ul>','guanyuofmall',NULL,'1',0,46);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (2,'admin','2016-04-04 15:55:49','admin','2016-04-04 15:55:49','注册协议','<span style=\"color:#333333;font-family:Ubuntu, Tahoma, \'Helvetica Neue\', Helvetica, Arial, sans-serif;line-height:2;font-size:14px;background-color:#FFFFFF;\">尊敬的用户欢迎您注册成为本网站会员。请用户仔细阅读以下全部内容。如用户不同意本服务条款任意内容，请不要注册或使用本网站服务。如用户通过本网站注册程序，即表示用户与本网站已达成协议，自愿接受本服务条款的所有内容。此后，用户不得以未阅读本服务条款内容作任何形式的抗辩。<br />\r\n一、本站服务条款的确认和接纳<br />\r\n本网站涉及的各项服务的所有权和运作权归本网站所有。本网站所提供的服务必须按照其发布的服务条款和操作规则严格执行。本服务条款的效力范围及于本网站的一切产品和服务，用户在享受本网站的任何服务时，应当受本服务条款的约束。<br />\r\n二、服务简介<br />\r\n本网站运用自己的操作系统通过国际互联网络为用户提供各项服务。用户必须: 1. 提供设备，如个人电脑、手机或其他上网设备。 2. 个人上网和支付与此服务有关的费用。<br />\r\n三、用户在不得在本网站上发布下列违法信息<br />\r\n1. 反对宪法所确定的基本原则的； 2. 危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的； 3. 损害国家荣誉和利益的； 4. 煽动民族仇恨、民族歧视，破坏民族团结的； 5. 破坏国家宗教政策，宣扬邪教和封建迷信的； 6. 散布谣言，扰乱社会秩序，破坏社会稳定的； 7. 散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的； 8. 侮辱或者诽谤他人，侵害他人合法权益的； 9. 含有法律、行政法规禁止的其他内容的。<br />\r\n四、有关个人资料<br />\r\n用户同意: 1. 提供及时、详尽及准确的个人资料。 2. 同意接收来自本网站的信息。 3. 不断更新注册资料，符合及时、详尽准确的要求。所有原始键入的资料将引用为注册资料。 4. 本网站不公开用户的姓名、地址、电子邮箱和笔名。除以下情况外: a) 用户授权本站透露这些信息。 b) 相应的法律及程序要求本站提供用户的个人资料。<br />\r\n五、服务条款的修改<br />\r\n本网站有权在必要时修改服务条款，一旦条款及服务内容产生变动，本网站将会在重要页面上提示修改内容。如果不同意所改动的内容，用户可以主动取消获得的本网站信息服务。如果用户继续享用本网站信息服务，则视为接受服务条款的变动。<br />\r\n六、用户隐私制度<br />\r\n尊重用户个人隐私是本网站的一项基本政策。所以，本网站一定不会在未经合法用户授权时公开、编辑或透露其注册资料及保存在本网站中的非公开内容，除非有法律许可要求或本网站在诚信的基础上认为透露这些信息在以下四种情况是必要的: 1. 遵守有关法律规定，遵从本网站合法服务程序。 2. 保持维护本网站的商标所有权。 3. 在紧急情况下竭力维护用户个人和社会大众的隐私安全。 4. 符合其他相关的要求。<br />\r\n七、用户的帐号、密码和安全性<br />\r\n用户一旦注册成功，将获得一个密码和用户名。用户需谨慎合理的保存、使用用户名和密码。如果你不保管好自己的帐号和密码安全，将负全部责任。另外，每个用户都要对其帐户中的所有活动和事件负全责。你可随时根据指示改变你的密码。用户若发现任何非法使用用户帐号或存在安全漏洞的情况，请立即通告本网站。 八、 拒绝提供担保 用户明确同意信息服务的使用由用户个人承担风险。本网站不担保服务不会受中断，对服务的及时性，安全性，出错发生都不作担保，但会在能力范围内，避免出错。<br />\r\n九、有限责任<br />\r\n如因不可抗力或其它本站无法控制的原因使本站销售系统崩溃或无法正常使用导致网上交易无法完成或丢失有关的信息、记录等本站会尽可能合理地协助处理善后事宜，并努力使客户免受经济损失，同时会尽量避免这种损害的发生。<br />\r\n十、用户信息的储存和限制<br />\r\n本站有判定用户的行为是否符合国家法律法规规定及本站服务条款权利，如果用户违背本网站服务条款的规定，本网站有权中断对其提供服务的权利。<br />\r\n十一、用户管理<br />\r\n用户单独承担发布内容的责任。用户对服务的使用是根据所有适用于本站的国家法律、地方法律和国际法律标准的。用户必须遵循: 1. 使用网络服务不作非法用途。 2. 不干扰或混乱网络服务。 3. 遵守所有使用网络服务的网络协议、规定、程序和惯例。 用户须承诺不传输任何非法的、骚扰性的、中伤他人的、辱骂性的、恐性的、伤害性的、庸俗的，淫秽等信息资料。另外，用户也不能传输何教唆他人构成犯罪行为的资料；不能传输助长国内不利条件和涉及国家安全的资料；不能传输任何不符合当地法规、国家法律和国际法律的资料。未经许可而非法进入其它电脑系统是禁止的。 若用户的行为不符合以上提到的服务条款，本站将作出独立判断立即取消用户服务帐号。用户需对自己在网上的行为承担法律责任。用户若在本站上散布和传播反动、色情或其它违反国家法律的信息，本站的系统记录有可能作为用户违反法律的证据。<br />\r\n十二、通告<br />\r\n所有发给用户的通告都可通过重要页面的公告或电子邮件或常规的信件传送。服务条款的修改、服务变更、或其它重要事件的通告都会以此形式进行。<br />\r\n十三、信息内容的所有权<br />\r\n本网站定义的信息内容包括: 文字、软件、声音、相片、录象、图表；在广告中全部内容；本网站为用户提供的其它信息。所有这些内容受版权、商标、标签和其它财产所有权法律的保护。所以，用户只能在本网站和广告商授权下才能使用这些内容，而不能擅自复制、再造这些内容、或创造与内容有关的派生产品。本站所有的文章版权归原文作者和本站共同所有，任何人需要转载本站的文章，必须征得原文作者或本站授权。<br />\r\n十四、法律<br />\r\n本协议的订立、执行和解释及争议的解决均应适用中华人民共和国的法律。用户和本网站一致同意服从本网站所在地有管辖权的法院管辖。如发生本网站服务条款与中华人民共和国法律相抵触时，则这些条款将完全按法律规定重新解释，而其它条款则依旧保持对用户的约束力。<br />\r\n</span><span style=\"color:#333333;font-family:Ubuntu, Tahoma, \'Helvetica Neue\', Helvetica, Arial, sans-serif;line-height:2;font-size:14px;background-color:#FFFFFF;\"></span>','zhucexieyi',NULL,'1',0,46);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (3,'admin','2016-04-04 15:58:03','admin','2016-04-04 15:58:03','购物指南','<p>\r\n	1. 注册成为会员\r\n</p>\r\n<p>\r\n	2. 添加物品到购物车\r\n</p>\r\n<p>\r\n	3. 购物车结算\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','gouwuzhinan',NULL,'1',0,47);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (4,'admin','2016-04-04 15:58:28','admin','2016-04-04 15:58:28','退货流程','<p>\r\n	退货\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	联系客服退货\r\n</p>','tuihuoliucheng',NULL,'1',0,47);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (5,'admin','2016-04-04 15:59:18','admin','2016-04-04 15:59:18','支付帮助','<p>\r\n	支持的支付方式\r\n</p>\r\n<p>\r\n	1. 支付宝\r\n</p>\r\n<p>\r\n	2. 线下支付\r\n</p>\r\n<p>\r\n	3. 电话支付\r\n</p>\r\n<p>\r\n	4. 财付通\r\n</p>','zhifubangzhu',NULL,'1',0,48);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (6,'admin','2016-04-04 16:00:06','admin','2016-04-04 16:00:06','配送指南','<p>\r\n	1. 填写收货地址\r\n</p>\r\n<p>\r\n	2. 选择配送方式\r\n</p>\r\n<p>\r\n	3. 选择配送时间\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','peisongzhinan',NULL,'1',0,51);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (7,'admin','2016-04-04 16:04:20','admin','2016-04-04 16:04:20','技术特色','<p>\r\n	1. 多种支持Cache类型\r\n</p>\r\n<p>\r\n	&nbsp; &nbsp; &nbsp;支持使用本地内存，Ehcache, Redis等多种Cache；更可以通过扩展CacheProvider支持更多Cache类型\r\n</p>\r\n<p>\r\n	2. 资源动静分离\r\n</p>\r\n<p>\r\n	&nbsp; &nbsp; 将图片或其他静态资源存放在单独的静态资源服务器，实现系统高性能，高可用\r\n</p>\r\n<p>\r\n	3. 内嵌式消息服务框架EMS\r\n</p>\r\n<p>\r\n	　通过自主研发的内嵌式消息服务框架，将订单/支付等过程解耦，支持高扩展性\r\n</p>\r\n<p>\r\n	4. 集群化部署方案\r\n</p>\r\n<p>\r\n	5. 支持前台页面皮肤自定义\r\n</p>','jishutese',NULL,'1',0,54);
INSERT INTO cms_article(id,create_account,create_time, update_account,update_time,title, content,code,read_count,is_valid,ordinal,category_id)
VALUES (8,'admin','2016-04-04 16:06:39','admin','2016-04-04 16:06:39','联系我们','<p>\r\n	欢迎提出您宝贵的意见和建议，共同为开源项目发展贡献力量！\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	项目主页：&nbsp;<a href=\"http://git.oschina.net/dinguangx/jshop\" target=\"_blank\">http://git.oschina.net/dinguangx/jshop</a>\r\n</p>\r\n<p>\r\n	QQ群：417059832\r\n</p>\r\n<p>\r\n	联系电话：13800138000\r\n</p>\r\n<p>\r\n	邮箱: dinguangx@163.com\r\n</p>','lianxiwomen',NULL,'1',0,55);

INSERT INTO cms_friend_link(id,create_account,create_time,update_account,update_time,link_name,link_url,link_logo,ordinal) VALUES (1,'admin','2016-04-04 16:25:43','admin','2016-04-04 16:25:43','淘宝网','www.taobao.com','',0);
INSERT INTO cms_friend_link(id,create_account,create_time,update_account,update_time,link_name,link_url,link_logo,ordinal) VALUES (2,'admin','2016-04-04 16:30:12','admin','2016-04-04 16:30:12','京东商城','www.jd.com','',2);
INSERT INTO cms_friend_link(id,create_account,create_time,update_account,update_time,link_name,link_url,link_logo,ordinal) VALUES (3,'admin','2016-04-04 16:30:47','admin','2016-04-04 16:30:47','亚马逊','www.amazon.cn','',3);
INSERT INTO cms_friend_link(id,create_account,create_time,update_account,update_time,link_name,link_url,link_logo,ordinal) VALUES (4,'admin','2016-04-04 16:31:01','admin','2016-04-04 16:31:16','支付宝','www.alipay.com','',4);
INSERT INTO cms_friend_link(id,create_account,create_time,update_account,update_time,link_name,link_url,link_logo,ordinal) VALUES (5,'admin','2016-04-04 16:31:11','admin','2016-04-04 16:32:09','财付通','www.tenpay.com','',5);

INSERT INTO cms_notice(id,create_account,create_time, update_account,update_time,title,content,read_count,is_valid,ordinal) VALUES (1,'admin','2016-04-04 16:49:23','admin','2016-04-04 16:51:29','Ofmall诞生了','Ofmall诞生了',0,'1',0);
INSERT INTO cms_notice(id,create_account,create_time, update_account,update_time,title,content,read_count,is_valid,ordinal) VALUES (2,'admin','2016-04-04 16:52:06','admin','2016-04-04 16:52:14','支付宝支付已加入Ofmall','支付宝支付已加入Ofmall支持列表',0,'1',0);

INSERT INTO member (id, create_account, create_time, update_account, update_time, username, nick_name, password, address, real_name, gender, email, birth_date, mobile, id_type, id_num, province, city, area, is_email_active, is_freeze, last_login_time, last_login_ip, last_login_area, regist_time, freeze_start_time, freeze_end_time, member_rank_id) VALUES (1, null, null, null, null, 'user', 'user', 'e10adc3949ba59abbe56e057f20f883e', null, null, '0', 'dinguangx@163.com', null, null, null, null, null, null, null, '1', '0', '2016-04-07 22:25:59', '0:0:0:0:0:0:0:1', '0', '2016-04-07 22:17:31', null, null, null);

