package net.jeeshop.biz.system.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemSettingExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public SystemSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_system_setting
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNull() {
            addCriterion("system_Code is null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNotNull() {
            addCriterion("system_Code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeEqualTo(String value) {
            addCriterion("system_Code =", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotEqualTo(String value) {
            addCriterion("system_Code <>", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThan(String value) {
            addCriterion("system_Code >", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_Code >=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThan(String value) {
            addCriterion("system_Code <", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThanOrEqualTo(String value) {
            addCriterion("system_Code <=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLike(String value) {
            addCriterion("system_Code like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotLike(String value) {
            addCriterion("system_Code not like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIn(List<String> values) {
            addCriterion("system_Code in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotIn(List<String> values) {
            addCriterion("system_Code not in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeBetween(String value1, String value2) {
            addCriterion("system_Code between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotBetween(String value1, String value2) {
            addCriterion("system_Code not between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andWwwIsNull() {
            addCriterion("www is null");
            return (Criteria) this;
        }

        public Criteria andWwwIsNotNull() {
            addCriterion("www is not null");
            return (Criteria) this;
        }

        public Criteria andWwwEqualTo(String value) {
            addCriterion("www =", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwNotEqualTo(String value) {
            addCriterion("www <>", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwGreaterThan(String value) {
            addCriterion("www >", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwGreaterThanOrEqualTo(String value) {
            addCriterion("www >=", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwLessThan(String value) {
            addCriterion("www <", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwLessThanOrEqualTo(String value) {
            addCriterion("www <=", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwLike(String value) {
            addCriterion("www like", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwNotLike(String value) {
            addCriterion("www not like", value, "www");
            return (Criteria) this;
        }

        public Criteria andWwwIn(List<String> values) {
            addCriterion("www in", values, "www");
            return (Criteria) this;
        }

        public Criteria andWwwNotIn(List<String> values) {
            addCriterion("www not in", values, "www");
            return (Criteria) this;
        }

        public Criteria andWwwBetween(String value1, String value2) {
            addCriterion("www between", value1, value2, "www");
            return (Criteria) this;
        }

        public Criteria andWwwNotBetween(String value1, String value2) {
            addCriterion("www not between", value1, value2, "www");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andShortcuticonIsNull() {
            addCriterion("shortcuticon is null");
            return (Criteria) this;
        }

        public Criteria andShortcuticonIsNotNull() {
            addCriterion("shortcuticon is not null");
            return (Criteria) this;
        }

        public Criteria andShortcuticonEqualTo(String value) {
            addCriterion("shortcuticon =", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonNotEqualTo(String value) {
            addCriterion("shortcuticon <>", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonGreaterThan(String value) {
            addCriterion("shortcuticon >", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonGreaterThanOrEqualTo(String value) {
            addCriterion("shortcuticon >=", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonLessThan(String value) {
            addCriterion("shortcuticon <", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonLessThanOrEqualTo(String value) {
            addCriterion("shortcuticon <=", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonLike(String value) {
            addCriterion("shortcuticon like", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonNotLike(String value) {
            addCriterion("shortcuticon not like", value, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonIn(List<String> values) {
            addCriterion("shortcuticon in", values, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonNotIn(List<String> values) {
            addCriterion("shortcuticon not in", values, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonBetween(String value1, String value2) {
            addCriterion("shortcuticon between", value1, value2, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andShortcuticonNotBetween(String value1, String value2) {
            addCriterion("shortcuticon not between", value1, value2, "shortcuticon");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIcpIsNull() {
            addCriterion("icp is null");
            return (Criteria) this;
        }

        public Criteria andIcpIsNotNull() {
            addCriterion("icp is not null");
            return (Criteria) this;
        }

        public Criteria andIcpEqualTo(String value) {
            addCriterion("icp =", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotEqualTo(String value) {
            addCriterion("icp <>", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpGreaterThan(String value) {
            addCriterion("icp >", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpGreaterThanOrEqualTo(String value) {
            addCriterion("icp >=", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpLessThan(String value) {
            addCriterion("icp <", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpLessThanOrEqualTo(String value) {
            addCriterion("icp <=", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpLike(String value) {
            addCriterion("icp like", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotLike(String value) {
            addCriterion("icp not like", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpIn(List<String> values) {
            addCriterion("icp in", values, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotIn(List<String> values) {
            addCriterion("icp not in", values, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpBetween(String value1, String value2) {
            addCriterion("icp between", value1, value2, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotBetween(String value1, String value2) {
            addCriterion("icp not between", value1, value2, "icp");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNull() {
            addCriterion("is_open is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNotNull() {
            addCriterion("is_open is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenEqualTo(String value) {
            addCriterion("is_open =", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotEqualTo(String value) {
            addCriterion("is_open <>", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThan(String value) {
            addCriterion("is_open >", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThanOrEqualTo(String value) {
            addCriterion("is_open >=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThan(String value) {
            addCriterion("is_open <", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThanOrEqualTo(String value) {
            addCriterion("is_open <=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLike(String value) {
            addCriterion("is_open like", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotLike(String value) {
            addCriterion("is_open not like", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenIn(List<String> values) {
            addCriterion("is_open in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotIn(List<String> values) {
            addCriterion("is_open not in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenBetween(String value1, String value2) {
            addCriterion("is_open between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotBetween(String value1, String value2) {
            addCriterion("is_open not between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andCloseMsgIsNull() {
            addCriterion("close_Msg is null");
            return (Criteria) this;
        }

        public Criteria andCloseMsgIsNotNull() {
            addCriterion("close_Msg is not null");
            return (Criteria) this;
        }

        public Criteria andCloseMsgEqualTo(String value) {
            addCriterion("close_Msg =", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgNotEqualTo(String value) {
            addCriterion("close_Msg <>", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgGreaterThan(String value) {
            addCriterion("close_Msg >", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgGreaterThanOrEqualTo(String value) {
            addCriterion("close_Msg >=", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgLessThan(String value) {
            addCriterion("close_Msg <", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgLessThanOrEqualTo(String value) {
            addCriterion("close_Msg <=", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgLike(String value) {
            addCriterion("close_Msg like", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgNotLike(String value) {
            addCriterion("close_Msg not like", value, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgIn(List<String> values) {
            addCriterion("close_Msg in", values, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgNotIn(List<String> values) {
            addCriterion("close_Msg not in", values, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgBetween(String value1, String value2) {
            addCriterion("close_Msg between", value1, value2, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andCloseMsgNotBetween(String value1, String value2) {
            addCriterion("close_Msg not between", value1, value2, "closeMsg");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andImageRootPathIsNull() {
            addCriterion("image_Root_Path is null");
            return (Criteria) this;
        }

        public Criteria andImageRootPathIsNotNull() {
            addCriterion("image_Root_Path is not null");
            return (Criteria) this;
        }

        public Criteria andImageRootPathEqualTo(String value) {
            addCriterion("image_Root_Path =", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathNotEqualTo(String value) {
            addCriterion("image_Root_Path <>", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathGreaterThan(String value) {
            addCriterion("image_Root_Path >", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathGreaterThanOrEqualTo(String value) {
            addCriterion("image_Root_Path >=", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathLessThan(String value) {
            addCriterion("image_Root_Path <", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathLessThanOrEqualTo(String value) {
            addCriterion("image_Root_Path <=", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathLike(String value) {
            addCriterion("image_Root_Path like", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathNotLike(String value) {
            addCriterion("image_Root_Path not like", value, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathIn(List<String> values) {
            addCriterion("image_Root_Path in", values, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathNotIn(List<String> values) {
            addCriterion("image_Root_Path not in", values, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathBetween(String value1, String value2) {
            addCriterion("image_Root_Path between", value1, value2, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andImageRootPathNotBetween(String value1, String value2) {
            addCriterion("image_Root_Path not between", value1, value2, "imageRootPath");
            return (Criteria) this;
        }

        public Criteria andManageHttpIsNull() {
            addCriterion("manage_Http is null");
            return (Criteria) this;
        }

        public Criteria andManageHttpIsNotNull() {
            addCriterion("manage_Http is not null");
            return (Criteria) this;
        }

        public Criteria andManageHttpEqualTo(String value) {
            addCriterion("manage_Http =", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpNotEqualTo(String value) {
            addCriterion("manage_Http <>", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpGreaterThan(String value) {
            addCriterion("manage_Http >", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpGreaterThanOrEqualTo(String value) {
            addCriterion("manage_Http >=", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpLessThan(String value) {
            addCriterion("manage_Http <", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpLessThanOrEqualTo(String value) {
            addCriterion("manage_Http <=", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpLike(String value) {
            addCriterion("manage_Http like", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpNotLike(String value) {
            addCriterion("manage_Http not like", value, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpIn(List<String> values) {
            addCriterion("manage_Http in", values, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpNotIn(List<String> values) {
            addCriterion("manage_Http not in", values, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpBetween(String value1, String value2) {
            addCriterion("manage_Http between", value1, value2, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andManageHttpNotBetween(String value1, String value2) {
            addCriterion("manage_Http not between", value1, value2, "manageHttp");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgIsNull() {
            addCriterion("default_Product_Img is null");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgIsNotNull() {
            addCriterion("default_Product_Img is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgEqualTo(String value) {
            addCriterion("default_Product_Img =", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgNotEqualTo(String value) {
            addCriterion("default_Product_Img <>", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgGreaterThan(String value) {
            addCriterion("default_Product_Img >", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgGreaterThanOrEqualTo(String value) {
            addCriterion("default_Product_Img >=", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgLessThan(String value) {
            addCriterion("default_Product_Img <", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgLessThanOrEqualTo(String value) {
            addCriterion("default_Product_Img <=", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgLike(String value) {
            addCriterion("default_Product_Img like", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgNotLike(String value) {
            addCriterion("default_Product_Img not like", value, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgIn(List<String> values) {
            addCriterion("default_Product_Img in", values, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgNotIn(List<String> values) {
            addCriterion("default_Product_Img not in", values, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgBetween(String value1, String value2) {
            addCriterion("default_Product_Img between", value1, value2, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andDefaultProductImgNotBetween(String value1, String value2) {
            addCriterion("default_Product_Img not between", value1, value2, "defaultProductImg");
            return (Criteria) this;
        }

        public Criteria andStyleIsNull() {
            addCriterion("style is null");
            return (Criteria) this;
        }

        public Criteria andStyleIsNotNull() {
            addCriterion("style is not null");
            return (Criteria) this;
        }

        public Criteria andStyleEqualTo(String value) {
            addCriterion("style =", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotEqualTo(String value) {
            addCriterion("style <>", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThan(String value) {
            addCriterion("style >", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThanOrEqualTo(String value) {
            addCriterion("style >=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThan(String value) {
            addCriterion("style <", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThanOrEqualTo(String value) {
            addCriterion("style <=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLike(String value) {
            addCriterion("style like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotLike(String value) {
            addCriterion("style not like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleIn(List<String> values) {
            addCriterion("style in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotIn(List<String> values) {
            addCriterion("style not in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleBetween(String value1, String value2) {
            addCriterion("style between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotBetween(String value1, String value2) {
            addCriterion("style not between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconIsNull() {
            addCriterion("manage_Left_Tree_Leaf_Icon is null");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconIsNotNull() {
            addCriterion("manage_Left_Tree_Leaf_Icon is not null");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconEqualTo(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon =", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconNotEqualTo(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon <>", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconGreaterThan(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon >", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconGreaterThanOrEqualTo(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon >=", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconLessThan(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon <", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconLessThanOrEqualTo(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon <=", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconLike(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon like", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconNotLike(String value) {
            addCriterion("manage_Left_Tree_Leaf_Icon not like", value, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconIn(List<String> values) {
            addCriterion("manage_Left_Tree_Leaf_Icon in", values, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconNotIn(List<String> values) {
            addCriterion("manage_Left_Tree_Leaf_Icon not in", values, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconBetween(String value1, String value2) {
            addCriterion("manage_Left_Tree_Leaf_Icon between", value1, value2, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andManageLeftTreeLeafIconNotBetween(String value1, String value2) {
            addCriterion("manage_Left_Tree_Leaf_Icon not between", value1, value2, "manageLeftTreeLeafIcon");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeIsNull() {
            addCriterion("statistics_Code is null");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeIsNotNull() {
            addCriterion("statistics_Code is not null");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeEqualTo(String value) {
            addCriterion("statistics_Code =", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeNotEqualTo(String value) {
            addCriterion("statistics_Code <>", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeGreaterThan(String value) {
            addCriterion("statistics_Code >", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("statistics_Code >=", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeLessThan(String value) {
            addCriterion("statistics_Code <", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeLessThanOrEqualTo(String value) {
            addCriterion("statistics_Code <=", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeLike(String value) {
            addCriterion("statistics_Code like", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeNotLike(String value) {
            addCriterion("statistics_Code not like", value, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeIn(List<String> values) {
            addCriterion("statistics_Code in", values, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeNotIn(List<String> values) {
            addCriterion("statistics_Code not in", values, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeBetween(String value1, String value2) {
            addCriterion("statistics_Code between", value1, value2, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andStatisticsCodeNotBetween(String value1, String value2) {
            addCriterion("statistics_Code not between", value1, value2, "statisticsCode");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveIsNull() {
            addCriterion("open_Responsive is null");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveIsNotNull() {
            addCriterion("open_Responsive is not null");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveEqualTo(String value) {
            addCriterion("open_Responsive =", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveNotEqualTo(String value) {
            addCriterion("open_Responsive <>", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveGreaterThan(String value) {
            addCriterion("open_Responsive >", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveGreaterThanOrEqualTo(String value) {
            addCriterion("open_Responsive >=", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveLessThan(String value) {
            addCriterion("open_Responsive <", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveLessThanOrEqualTo(String value) {
            addCriterion("open_Responsive <=", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveLike(String value) {
            addCriterion("open_Responsive like", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveNotLike(String value) {
            addCriterion("open_Responsive not like", value, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveIn(List<String> values) {
            addCriterion("open_Responsive in", values, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveNotIn(List<String> values) {
            addCriterion("open_Responsive not in", values, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveBetween(String value1, String value2) {
            addCriterion("open_Responsive between", value1, value2, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andOpenResponsiveNotBetween(String value1, String value2) {
            addCriterion("open_Responsive not between", value1, value2, "openResponsive");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateAccountIsNull() {
            addCriterion("create_Account is null");
            return (Criteria) this;
        }

        public Criteria andCreateAccountIsNotNull() {
            addCriterion("create_Account is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAccountEqualTo(String value) {
            addCriterion("create_Account =", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountNotEqualTo(String value) {
            addCriterion("create_Account <>", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountGreaterThan(String value) {
            addCriterion("create_Account >", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountGreaterThanOrEqualTo(String value) {
            addCriterion("create_Account >=", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountLessThan(String value) {
            addCriterion("create_Account <", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountLessThanOrEqualTo(String value) {
            addCriterion("create_Account <=", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountLike(String value) {
            addCriterion("create_Account like", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountNotLike(String value) {
            addCriterion("create_Account not like", value, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountIn(List<String> values) {
            addCriterion("create_Account in", values, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountNotIn(List<String> values) {
            addCriterion("create_Account not in", values, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountBetween(String value1, String value2) {
            addCriterion("create_Account between", value1, value2, "createAccount");
            return (Criteria) this;
        }

        public Criteria andCreateAccountNotBetween(String value1, String value2) {
            addCriterion("create_Account not between", value1, value2, "createAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountIsNull() {
            addCriterion("update_Account is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountIsNotNull() {
            addCriterion("update_Account is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountEqualTo(String value) {
            addCriterion("update_Account =", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountNotEqualTo(String value) {
            addCriterion("update_Account <>", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountGreaterThan(String value) {
            addCriterion("update_Account >", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountGreaterThanOrEqualTo(String value) {
            addCriterion("update_Account >=", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountLessThan(String value) {
            addCriterion("update_Account <", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountLessThanOrEqualTo(String value) {
            addCriterion("update_Account <=", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountLike(String value) {
            addCriterion("update_Account like", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountNotLike(String value) {
            addCriterion("update_Account not like", value, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountIn(List<String> values) {
            addCriterion("update_Account in", values, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountNotIn(List<String> values) {
            addCriterion("update_Account not in", values, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountBetween(String value1, String value2) {
            addCriterion("update_Account between", value1, value2, "updateAccount");
            return (Criteria) this;
        }

        public Criteria andUpdateAccountNotBetween(String value1, String value2) {
            addCriterion("update_Account not between", value1, value2, "updateAccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_system_setting
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_system_setting
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}